Add quite odd but not that unfrequent real-life usecase
There is a possibility when:
* an action on AggregateRoot is performed which does not apply any
  events, its unpublished_events array is empty
* AggregateRoot::repository reads an empty array of unpublished_events
  and publishes it without checking that it is empty
to trigger this code path of `append_to_stream([])`

Previously activerecord-import handled it with grace. AR#insert_all
loudly protests when receiving empty list:

  ArgumentError: Empty list of attributes passed

Therefore we have to exit early.